version: '3'

services:

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9100:9000
      - 9101:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always
    volumes:
      - minio_storage:/data
      
  varmax:
    build: .
    ports:
      - "80:80"
    restart: always

volumes:
  minio_storage: {}
